server:
  port: 8080

spring:
  application:
    name: aws-lab-backend
  datasource:
    url: jdbc:mysql://database-1-instance-1.c52ou2cc4zwt.ap-northeast-2.rds.amazonaws.com:3306/mysql?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: admintest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true